from telebot import types

nums          = types.ReplyKeyboardMarkup(row_width=9, resize_keyboard=True, one_time_keyboard=True)
YesNo         = types.ReplyKeyboardMarkup(row_width=2, resize_keyboard=True, one_time_keyboard=True)
Regions       = types.ReplyKeyboardMarkup(row_width=3, resize_keyboard=True, one_time_keyboard=True)
Countries     = types.ReplyKeyboardMarkup(row_width=4, resize_keyboard=True, one_time_keyboard=True)
percent       = types.ReplyKeyboardMarkup(row_width=5, resize_keyboard=True, one_time_keyboard=True)
mobilizade    = types.ReplyKeyboardMarkup(row_width=4, resize_keyboard=True, one_time_keyboard=True)
relocate_info = types.ReplyKeyboardMarkup(row_width=7, resize_keyboard=True, one_time_keyboard=True)
need_some_k   = types.ReplyKeyboardMarkup(row_width=1, resize_keyboard=True, one_time_keyboard=True)
topic         = types.ReplyKeyboardMarkup(row_width=3, resize_keyboard=True, one_time_keyboard=True)

One           = types.KeyboardButton(text='1')
Two           = types.KeyboardButton(text='2')
Three         = types.KeyboardButton(text='3')
Four          = types.KeyboardButton(text='4')
Five          = types.KeyboardButton(text='5')
Six           = types.KeyboardButton(text='6')
Seven         = types.KeyboardButton(text='7')
Eight         = types.KeyboardButton(text='8')
Nine          = types.KeyboardButton(text='9')
Back          = types.KeyboardButton(text='Back')

Yes           = types.KeyboardButton(text='Yes')
No            = types.KeyboardButton(text='No')
Back          = types.KeyboardButton(text='Back')

Kiyv_r        = types.KeyboardButton(text='Kyiv')
Kharkiv_r     = types.KeyboardButton(text='Kharkiv')
Lviv_r        = types.KeyboardButton(text='Lviv')
IF_r          = types.KeyboardButton(text='Ivano-Frankivsk')
Zakarpattia_r = types.KeyboardButton(text='Zakarpattia')
Ternopil_r    = types.KeyboardButton(text='Ternopil')
Poltava_r     = types.KeyboardButton(text='Poltava')
Dnipro_r      = types.KeyboardButton(text='Dnipro')
Rivne_r       = types.KeyboardButton(text='Rivne')

Out_of_Ukraine= types.KeyboardButton(text='Out of Ukraine')

Ukraine       = types.KeyboardButton(text='Ukraine')
Poland        = types.KeyboardButton(text='Poland')
Germany       = types.KeyboardButton(text='Germany')
Italy         = types.KeyboardButton(text='Italy')

quater        = types.KeyboardButton(text='25%')
half          = types.KeyboardButton(text='50%')
seventy_five  = types.KeyboardButton(text='75%')
full          = types.KeyboardButton(text='100%')
Back_         = types.KeyboardButton(text='Back')

yes_TrO       = types.KeyboardButton(text='Territorial Defense')
yes_army      = types.KeyboardButton(text='The Armed Forces of Ukraine')
no            = types.KeyboardButton(text='No')

Back          = types.KeyboardButton(text='Back')

One           = types.KeyboardButton(text='1')
Two           = types.KeyboardButton(text='2')
Three         = types.KeyboardButton(text='3')
Four          = types.KeyboardButton(text='4')
Five          = types.KeyboardButton(text='5')
Six           = types.KeyboardButton(text='6')
Seven         = types.KeyboardButton(text='7')
Female        = types.KeyboardButton(text='Female')
Back          = types.KeyboardButton(text='Back')

Software     = types.KeyboardButton(text='Software')
Equipment     = types.KeyboardButton(text='Hardware')
Supplies      = types.KeyboardButton(text='Supplies\n(Food, water, medical)')
# Medical       = types.KeyboardButton(text='Medical')
# Water         = types.KeyboardButton(text='Water')
Nothing       = types.KeyboardButton(text='Nothing')
Back          = types.KeyboardButton(text='Back')


Location      = types.KeyboardButton(text='Location')
Mobilizate    = types.KeyboardButton(text='Mobilization status')
Can_work      = types.KeyboardButton(text='Possibility to work')
Productivity  = types.KeyboardButton(text='Productivity')
# Safe_mark     = types.KeyboardButton(text='Safe mark')
Relocate      = types.KeyboardButton(text='Relocation')
Resources     = types.KeyboardButton(text='Resources')


nums.add(One, Two, Three, Four, Five, Six, Seven, Eight, Nine, Back)
YesNo.add(Yes,No, Back)
# Cities.add(Kiyv,Kharkiv,Lviv)
Regions.add(Kiyv_r,Kharkiv_r,Lviv_r,Zakarpattia_r,IF_r,Ternopil_r,Poltava_r,Dnipro_r,Rivne_r,Out_of_Ukraine)
percent.add(quater, half, seventy_five, full, Back_)
mobilizade.add(yes_TrO, yes_army, no, Back)
Countries.add(Poland,Germany,Italy)
relocate_info.add(One, Two, Three, Four, Five, Six, Seven,Female, Back)
need_some_k.add(Software,Equipment,Supplies,Nothing,Back)
topic.add(Location,Mobilizate,Can_work,Productivity,Relocate,Resources,Nothing)
