CHATID serial PRIMARY KEY,
  USERNAME TEXT,
  NAME_SURNAME TEXT,
  MAIL TEXT,
  ISVERIFIED BOOLEAN,
  ISREGISTRED BOOLEAN,
  ISACTUAL BOOLEAN,
  REASON TEXT,
  MOBILIZED_DATA TEXT,
  COUNTRY TEXT,
  CITY TEXT,
  MOBILIZADE TEXT,
  SAFE_MARK TEXT,
  CAN_WORK BOOLEAN,
  PRODUCTIVITY TEXT,
  ALLNEED BOOLEAN,
  NEEDTECH TEXT,
  NEEDMED BOOLEAN,
  NEEDMED_INFO TEXT,
  NEEDEAT BOOLEAN,
  NEEDEAT_INFO TEXT,
  NEEDWATER BOOLEAN,
  NEEDWATER_INFO TEXT,
  READY_TO_RELOCATE BOOLEAN,
  ADDITIONAL TEXT,    ?
  LANGUAGE TEXT,      ?
  DIFFICULTIES TEXT,
  NEEDRESOURCES BOOLEAN,
  NEEDRESOURCES_INFO TEXT,
  READY_TO_RELOCATE_INFO TEXT,
  LOCATION BOOLEAN,
  LOCATION_INFO TEXT
__________________________________________________________________________________________________________________________________________________________________________________________________________________________

CHATID serial PRIMARY KEY,
  USERNAME TEXT,
  NAME_SURNAME TEXT,
  MAIL TEXT,
  ISVERIFIED BOOLEAN,
  ISREGISTRED BOOLEAN,
  LAST_DATE TEXT,
  LOCATION_REGION TEXT,
  IS_LOCATION_REGION_CENTER BOOLEAN,
  LOCATION_CITY TEXT,
  COUNTRY TEXT,
  PLAN_RELOCATE BOOLEAN,
  PLAN_RELOCATE_INFO TEXT,
  READY_TO_RELOCATE_OUTSIDE BOOLEAN,
  READY_TO_RELOCATE_OUTSIDE_INFO TEXT,
  MOBILIZADE TEXT,
  MOBILIZADE_DATE TEXT,
  CAN_WORK BOOLEAN,
  CAN_WORK_REASON TEXT,
  PRODUCTIVITY TEXT,
  PRODUCTIVITY_DIFFICULTIES TEXT,
  NEED_EQUIPMENT BOOLEAN,
  NEED_EQUIPMENT_INFO TEXT,
  NEED_RESOURCES BOOLEAN,
  NEED_RESOURCES_INFO TEXT,
  SAFE_MARK TEXT,
  NEEDMED BOOLEAN,
  NEEDMED_INFO TEXT,
  NEEDEAT BOOLEAN,
  NEEDEAT_INFO TEXT,
  NEEDWATER BOOLEAN,
  NEEDWATER_INFO TEXT,
  NEEDHELP_INFO TEXT
 chatid, username, name_surname, mail, isverified, isregistered, las_date, location_region, is_location_region_center, location_city, country, plan_relocate, plan_relocate_info, ready_to_relocate_outside, ready_to_relocate_outside_info, mobilizade, mobilizade_date, can_work, can_work_reason, productivity, productivity_difficulties, need_equipment, need_equipment_info, need_resources, need_resources_info, safe_mark,needmed, needmed_info, needeat, needeat_info, needwater, needwater_info, needhelp_info
