en_msg_start               ='Hello, please, indicate your Globallogic email address '
en_msg_help                ='Help'
en_msg_welcome             ="Hello, you can get detailed information using the command /help"
en_msg_already_registered  ="You are already registered"
en_msg_unregistered        ="Для користування ботом пройдіть реєстрацію. Для цього скористайтесь командою /registration"

en_msg_behalf_collegue     ="I answer on behalf of my collegue:\nIndicate the GlobalLogic mail of collegue"
en_msg_wait_msg            ="Please, type the message"
en_msg_not_permot          ="Command is not permitted"
en_msg_data_actualized     ="Thanks, data is actualized"
en_msg_error_type          ="You can't type here. Please, follow the buttons.\nIn case of emergency, use /sos command"
en_msg_error_use_but       ="Please, use buttons for this answer"

en_msg_verification_code   ="A verification code has been sent to your email, please enter it in the message without spaces:"
en_msg_error_email         ="Mail is not valide\nTry one more time"
en_msg_ok_verification     ="Thank you, you are successfully registered"
en_msg_error_verification  ="Wrong verification code\nPlease,use command /registration for one more try"

en_msg_problem_description ="Please describe exactly you problem in one message"

en_msg_update_section      ="Please, chose section for update"
en_msg_updated             ="Information has been seccesfully updated"
en_msg_сity_option         ="Please, indicate your current city location. If your city is not on the list, write it down (ONLY regional center or the region)"
en_msg_is_reg_centr        ="Please, specify do you locate in the regional center?"
en_msg_сountry_option      ="Please, specify your country. Is not on the list, write it down"
en_msg_location_option     ="Please, specify your city/vilage location."

en_msg_mobilizade          ="Are you mobilized to The Armed Forces of Ukraine or joined Territorial defense (Teroborona)?"
en_msg_when                ="Since when?"
en_q_diff                  ="Please, let us know what makes difficulties?"
# en_msg_safe                ="How safe are you? Rate from 1 to 9\nWhere 9 means completely safe, 1 - critically dangerous"
en_q_relocate              ="Can you relocate outside of Ukraine (except to martial law)? "
en_msg_relocate            ="If you are a male, please, indicate the reason why, You have/you are:\n1) certificate of recruitment deferral and message on enrollment to\n2) special military registration conclusion of military and medical commission on ineligibility\n3) maintain three or more children aged to 18 y.o\n4) raise alone a child (children) aged to 18 y.o.\n5) adopter/guardian\n6) immediate family members perished or disappeared during the antiterrorist operation\n7) the reason is reported to manager"
en_q_location              ="Do you plan to change location?"
en_msg_location            ="Where and when?"
en_q_need_med              ="Do you have enough medicines for the next 2 weeks?"
en_q_supplies              ="Please, specify if you need something from this list:"
en_q_supplies_more         ="Please, indicate, do you need something more from this list?"
en_q_more_help             ="Please indicate if you need any additional help."
en_msg_more_help           ="Please describe exactly what you need in one message"
en_q_can_work              ="Are you able to work?"
en_q_can_work_still        ="You declared, that you can't work, is it actual?"
en_q_productivity          ="Please, evaluate your capability of work in percentage (PLS indicate with '%' sign)"
en_msg_reason              ="Please, let us know what is the reason?"

en_mag_poss_reloc1         ="certificate of recruitment deferral and message on enrollment to"
en_mag_poss_reloc2         ="special military registration conclusion of military and medical commission on ineligibility"
en_mag_poss_reloc3         ="maintain three or more children aged to 18 y.o"
en_mag_poss_reloc4         ="raise alone a child (children) aged to 18 y.o."
en_mag_poss_reloc5         ="adopter/guardian"
en_mag_poss_reloc6         ="immediate family members perished or disappeared during the antiterrorist operation"
en_mag_poss_reloc7         ="the reason is reported to manager"
en_mag_poss_reloc8         ="Female"

en_msg_need_sup            ="Please describe in one message:\n\nHow long do you have enough supplies for?\nDo you need to be provided with some supplies in the near future?\nWhat exactly do you need?"
en_q_all_need              ="Do you have all the requirement equipment to do your work?"
en_msg_need_equipment      ="Please, indicate what equipment do you need"
en_q_need_resources        ="Do you have access to the needed resources?"
en_msg_need_resources      ="Please, indicate what resource is missed"
en_msg_finish_q            ="Thank you for your answers, we will contact you if necessary"
en_msg_finish_reg          ="Thank you, you are successfully registered"
en_msg_finish_sos          ="Thanks, we will contact you as soon as possible."
en_msg_error_email         ="Mail is not valide"
